import { readFileSync } from 'node:fs'
import { test } from 'node:test'
import assert from 'node:assert/strict'

const page = readFileSync(new URL('../app/pages/drama/[id]/episode/[episodeNumber].vue', import.meta.url), 'utf8')
const studioCss = readFileSync(new URL('../app/assets/studio.css', import.meta.url), 'utf8')
const apiSource = readFileSync(new URL('../app/composables/useApi.ts', import.meta.url), 'utf8')

test('episode workbench uses the approved storyboard-first video flow', () => {
  assert.match(page, /角色与场景/)
  assert.match(page, /分镜拆分/)
  assert.match(page, /视频生成/)
  assert.match(page, /pipelineTotal/)
  assert.match(page, /const pipelineTotal = 6/)
  assert.doesNotMatch(page, /镜头设计/)
  assert.doesNotMatch(page, /pipelineProgress\s*}}\/11/)
  assert.doesNotMatch(page, /pipelineProgress\s*\/\s*11/)
  assert.doesNotMatch(page, /角色\/场景资产/)
  assert.match(page, /prod:assets/)
  assert.match(page, /prodTab === 'assets'/)
  assert.doesNotMatch(page, /script:storyboard/)
  assert.doesNotMatch(page, /分配音色/)
})

test('production includes the role and scene workspace before storyboard split', () => {
  const sidebarStart = page.indexOf('const sidebarSections')
  const sidebarEnd = page.indexOf('const activeMainStage', sidebarStart)
  assert.ok(sidebarStart > -1 && sidebarEnd > sidebarStart, 'sidebar section definition is present')
  const sidebarBlock = page.slice(sidebarStart, sidebarEnd)
  const scriptSectionStart = sidebarBlock.indexOf("id: 'script'")
  const productionSectionStart = sidebarBlock.indexOf("id: 'production'")
  const exportSectionStart = sidebarBlock.indexOf("id: 'export'")
  assert.ok(scriptSectionStart > -1, 'script sidebar section is present')
  assert.ok(productionSectionStart > scriptSectionStart, 'production sidebar section follows script')
  assert.ok(exportSectionStart > productionSectionStart, 'export sidebar section follows production')

  const scriptSection = sidebarBlock.slice(scriptSectionStart, productionSectionStart)
  const productionSection = sidebarBlock.slice(productionSectionStart, exportSectionStart)

  assert.doesNotMatch(scriptSection, /script:storyboard/)
  assert.doesNotMatch(scriptSection, /script:extract/)
  const assetsIdx = productionSection.indexOf("key: 'prod:assets'")
  const storyboardIdx = productionSection.indexOf("key: 'prod:storyboard'")
  const videosIdx = productionSection.indexOf("key: 'prod:videos'")
  assert.ok(assetsIdx > -1, 'role and scene workspace is in production')
  assert.ok(storyboardIdx > assetsIdx, 'storyboard split follows role and scene workspace')
  assert.ok(videosIdx > storyboardIdx, 'video generation follows storyboard split')
  assert.match(productionSection, /label: '角色与场景'/)
  assert.match(productionSection, /label: '分镜拆分'/)
  assert.doesNotMatch(productionSection, /镜头设计/)
})

test('post-video dubbing is not exposed as a production step', () => {
  assert.doesNotMatch(page, /prod:dubbing/)
  assert.doesNotMatch(page, /id:\s*'dubbing'/)
  assert.doesNotMatch(page, /prodTab === 'dubbing'/)
  assert.doesNotMatch(page, /配音生成/)
  assert.doesNotMatch(page, /生成配音/)
  assert.doesNotMatch(page, /batchShotTTS/)
  assert.doesNotMatch(page, /genShotTTS/)
})

test('video composition is not exposed as a production step', () => {
  assert.doesNotMatch(page, /prod:compose/)
  assert.doesNotMatch(page, /id:\s*'compose'/)
  assert.doesNotMatch(page, /prodTab === 'compose'/)
  assert.doesNotMatch(page, /视频合成/)
  assert.doesNotMatch(page, /composeAPI/)
  assert.doesNotMatch(page, /doCompose/)
  assert.doesNotMatch(page, /batchCompose/)
  assert.doesNotMatch(page, /pollComposeStatus/)
  assert.match(page, /const pipelineTotal = 6/)
})

test('storyboard split exposes the generated shot information and prompt editor', () => {
  const storyboardStart = page.indexOf("prodTab === 'storyboard'")
  const videoStart = page.indexOf("prodTab === 'videos'", storyboardStart)
  assert.ok(storyboardStart > -1 && videoStart > storyboardStart, 'storyboard split section is present before video generation')
  const storyboardBlock = page.slice(storyboardStart, videoStart)

  assert.match(storyboardBlock, /class="storyboard-workbench"/)
  assert.match(storyboardBlock, /分镜列表/)
  assert.match(storyboardBlock, /class="storyboard-shot-card"/)
  assert.match(storyboardBlock, /class="storyboard-editor-main"/)
  assert.match(storyboardBlock, /class="storyboard-summary-strip"/)
  assert.match(storyboardBlock, /开始拆分/)
  assert.match(storyboardBlock, /重新拆分/)
  assert.match(storyboardBlock, /selectedSb/)
  assert.match(storyboardBlock, /时长/)
  assert.match(storyboardBlock, /动作/)
  assert.match(storyboardBlock, /画面描述/)
  assert.match(storyboardBlock, /对白 \/ 旁白/)
  assert.match(storyboardBlock, /氛围/)
  assert.match(storyboardBlock, /视频提示词/)
  assert.match(storyboardBlock, /updateField\(selectedSb, 'video_prompt'/)
  assert.match(storyboardBlock, /绑定角色/)
  assert.match(storyboardBlock, /绑定场景/)
  assert.doesNotMatch(storyboardBlock, /基础信息/)
  assert.doesNotMatch(storyboardBlock, /标题/)
  assert.doesNotMatch(storyboardBlock, /景别/)
  assert.doesNotMatch(storyboardBlock, /角度/)
  assert.doesNotMatch(storyboardBlock, /结果/)
  assert.doesNotMatch(storyboardBlock, /updateField\(selectedSb, 'title'/)
  assert.doesNotMatch(storyboardBlock, /updateField\(selectedSb, 'shot_type'/)
  assert.doesNotMatch(storyboardBlock, /updateField\(selectedSb, 'angle'/)
  assert.doesNotMatch(storyboardBlock, /updateField\(selectedSb, 'result'/)
  assert.doesNotMatch(storyboardBlock, /生成首尾帧/)
  assert.doesNotMatch(storyboardBlock, /genShotFrame/)
})

test('storyboard breaker prompt only requires production fields used by the UI', () => {
  assert.match(page, /绑定角色/)
  const agentSource = readFileSync(new URL('../../backend/src/agents/index.ts', import.meta.url), 'utf8')
  const storyboardPromptStart = agentSource.indexOf('storyboard_breaker')
  const gridPromptStart = agentSource.indexOf('grid_prompt_generator', storyboardPromptStart)
  const storyboardPrompt = agentSource.slice(storyboardPromptStart, gridPromptStart)

  assert.match(storyboardPrompt, /character_ids/)
  assert.match(storyboardPrompt, /scene_id/)
  assert.match(storyboardPrompt, /duration/)
  assert.match(storyboardPrompt, /action/)
  assert.match(storyboardPrompt, /description/)
  assert.match(storyboardPrompt, /dialogue/)
  assert.match(storyboardPrompt, /atmosphere/)
  assert.match(storyboardPrompt, /video_prompt/)
  assert.doesNotMatch(storyboardPrompt, /shot_type/)
  assert.doesNotMatch(storyboardPrompt, /angle/)
  assert.doesNotMatch(storyboardPrompt, /result/)
  assert.doesNotMatch(storyboardPrompt, /bgm_prompt/)
  assert.doesNotMatch(storyboardPrompt, /sound_effect/)
})

test('storyboard split shows a right-side reference asset rail', () => {
  const storyboardStart = page.indexOf("prodTab === 'storyboard'")
  const videoStart = page.indexOf("prodTab === 'videos'", storyboardStart)
  const storyboardBlock = page.slice(storyboardStart, videoStart)

  assert.match(storyboardBlock, /class="storyboard-reference-panel"/)
  assert.match(storyboardBlock, /参考素材/)
  assert.match(storyboardBlock, /getShotReferenceAssets\(selectedSb\)/)
  assert.match(storyboardBlock, /将作为视频参考图/)
  assert.match(storyboardBlock, /未生成/)
  assert.match(page, /function getShotReferenceAssets\(sb\)/)
  assert.match(page, /function getStoryboardScene\(sb\)/)
  assert.match(page, /function getStoryboardCharacters\(sb\)/)
})

test('storyboard split uses dark dense list styling instead of bright note cards', () => {
  assert.match(page, /\.storyboard-workbench\s*\{[\s\S]*?grid-template-columns:\s*300px minmax\(0,\s*1fr\) 280px/)
  assert.match(page, /\.storyboard-shot-card\s*\{[\s\S]*?background:\s*var\(--surface-muted\)/)
  assert.match(page, /\.storyboard-shot-card\.active\s*\{[\s\S]*?border-left-color:\s*var\(--accent\)/)
  assert.doesNotMatch(page, /\.storyboard-shot-card\s*\{[\s\S]*?background:\s*#fff/)
  assert.match(page, /\.storyboard-reference-panel\s*\{[\s\S]*?background:\s*var\(--surface-muted\)/)
})

test('video generation exposes a referenced task list from storyboard split', () => {
  const videoStart = page.indexOf("prodTab === 'videos'")
  const videoEnd = page.indexOf('<!-- Production Navigator -->', videoStart)
  assert.ok(videoStart > -1 && videoEnd > videoStart, 'video generation section is present')
  const videoBlock = page.slice(videoStart, videoEnd)

  assert.match(videoBlock, /class="video-task-list"/)
  assert.match(videoBlock, /AI 生成分镜/)
  assert.match(videoBlock, /doBreakdown/)
  assert.match(videoBlock, /videoTaskRows/)
  assert.match(videoBlock, /videoTaskState/)
  assert.match(videoBlock, /videoTaskStatusLabel/)
  assert.match(videoBlock, /videoTaskFailedCount/)
  assert.match(videoBlock, /参考素材/)
  assert.match(videoBlock, /task\.referenceCount/)
  assert.match(videoBlock, /genVid\(task\.storyboard\)/)
  assert.doesNotMatch(videoBlock, /缺参考图/)
  assert.doesNotMatch(videoBlock, /补参考图/)
  assert.doesNotMatch(videoBlock, /goSubStep\('script:storyboard'\)/)
})

test('video generation sends character and scene images as multiple references', () => {
  assert.match(page, /function getShotReferenceImages\(sb\)/)
  assert.match(page, /getStoryboardCharacterIds\(sb\)/)
  assert.match(page, /scene\?\.image_url \|\| scene\?\.imageUrl/)
  assert.match(page, /char\?\.image_url \|\| char\?\.imageUrl/)
  assert.match(page, /reference_mode: referenceImages\.length \? 'multiple' : 'none'/)
  assert.match(page, /reference_image_urls: referenceImages/)
  assert.doesNotMatch(page, /reference_mode: 'none'/)
})

test('production exposes the previous role and scene card workbench', () => {
  const assetStart = page.indexOf("prodTab === 'assets'")
  const storyboardStart = page.indexOf("prodTab === 'storyboard'", assetStart)
  assert.ok(assetStart > -1 && storyboardStart > assetStart, 'role and scene workbench appears before storyboard split')
  const assetBlock = page.slice(assetStart, storyboardStart)

  assert.match(assetBlock, /角色资产/)
  assert.match(assetBlock, /场景图片/)
  assert.match(assetBlock, /class="character-asset-grid"/)
  assert.match(assetBlock, /class="card character-asset-card"/)
  assert.match(assetBlock, /class="card asset-card asset-click-card"/)
  assert.match(assetBlock, /doExtract/)
  assert.match(assetBlock, /开始提取/)
  assert.match(assetBlock, /重新提取/)
  assert.match(assetBlock, /角色和场景会在提取后显示在这里/)
  assert.match(assetBlock, /batchCharImages/)
  assert.match(assetBlock, /batchSceneImages/)
  assert.match(page, /prodTab\.value = 'assets'/)
  assert.match(page, /openAssetDetail\('character'/)

  assert.doesNotMatch(page, /asset-detail-voice-panel/)
  assert.doesNotMatch(page, /角色音色/)
  assert.doesNotMatch(page, /updateCharVoice/)
  assert.doesNotMatch(page, /previewVoiceSample/)
})

test('asset detail fields are reduced to character styling and scene lighting semantics', () => {
  const assetDetailStart = page.indexOf('assetDetail.open && assetDetail.item')
  const imageViewerStart = page.indexOf('imageViewer.open && imageViewer.src', assetDetailStart)
  assert.ok(assetDetailStart > -1 && imageViewerStart > assetDetailStart, 'asset detail dialog is present')

  const detailBlock = page.slice(assetDetailStart, imageViewerStart)

  assert.match(page, /characterVisualSummary/)
  assert.match(page, /characterStylingValue/)
  assert.match(page, /sceneLightingValue/)
  assert.match(detailBlock, /样貌/)
  assert.match(detailBlock, /妆造/)
  assert.match(detailBlock, /场景描述/)
  assert.match(detailBlock, /场景光影/)
  assert.match(detailBlock, /asset-detail-edit-grid/)
  assert.match(detailBlock, /assetDetailDraft\.appearance/)
  assert.match(detailBlock, /assetDetailDraft\.styling/)
  assert.match(detailBlock, /assetDetailDraft\.prompt/)
  assert.match(detailBlock, /assetDetailDraft\.lighting/)
  assert.match(detailBlock, /saveAssetDetail/)
  assert.doesNotMatch(detailBlock, /试听文件/)
  assert.doesNotMatch(detailBlock, /图片状态/)
  assert.doesNotMatch(detailBlock, /关联镜头/)
  assert.doesNotMatch(detailBlock, /assetDetailRelatedShots/)
  assert.doesNotMatch(detailBlock, /asset-detail-shot-list/)
  assert.doesNotMatch(detailBlock, /asset-detail-grid/)
  assert.doesNotMatch(detailBlock, /性格/)
  assert.doesNotMatch(detailBlock, /assetDetail\.item\.personality/)
})

test('asset detail dialog uses a focused preview and editor composition', () => {
  const assetDetailStart = page.indexOf('assetDetail.open && assetDetail.item')
  const imageViewerStart = page.indexOf('imageViewer.open && imageViewer.src', assetDetailStart)
  assert.ok(assetDetailStart > -1 && imageViewerStart > assetDetailStart, 'asset detail dialog is present')

  const detailBlock = page.slice(assetDetailStart, imageViewerStart)
  assert.match(detailBlock, /class="asset-detail-shell"/)
  assert.match(detailBlock, /class="asset-detail-preview-panel"/)
  assert.match(detailBlock, /class="asset-detail-editor-panel"/)
  assert.match(detailBlock, /class="asset-detail-section-title"/)
  assert.match(detailBlock, /class="asset-detail-primary-actions"/)
  assert.match(detailBlock, /asset-detail-meta-row/)
  assert.match(detailBlock, /视觉预览/)
  assert.match(detailBlock, /编辑信息/)
})

test('character asset detail gives appearance and styling full-width editors', () => {
  const assetDetailStart = page.indexOf('assetDetail.open && assetDetail.item')
  const imageViewerStart = page.indexOf('imageViewer.open && imageViewer.src', assetDetailStart)
  assert.ok(assetDetailStart > -1 && imageViewerStart > assetDetailStart, 'asset detail dialog is present')

  const detailBlock = page.slice(assetDetailStart, imageViewerStart)
  assert.match(detailBlock, /asset-detail-edit-grid--\$\{assetDetail\.type\}/)
  assert.match(detailBlock, /assetDetailDraft\.appearance[\s\S]*rows="6"/)
  assert.match(detailBlock, /assetDetailDraft\.styling[\s\S]*rows="6"/)
  assert.match(page, /\.asset-detail-edit-grid--character\s*\{[\s\S]*?grid-template-columns:\s*1fr/)
  assert.match(page, /\.asset-detail-edit-grid--character \.asset-detail-textarea\s*\{[\s\S]*?min-height:\s*164px/)
})

test('script flow no longer exposes a role and scene review screen', () => {
  const scriptPanelStart = page.indexOf("panel === 'script'")
  const productionPanelStart = page.indexOf("panel === 'production'", scriptPanelStart)
  assert.ok(scriptPanelStart > -1 && productionPanelStart > scriptPanelStart, 'script panel block is present')
  const scriptPanel = page.slice(scriptPanelStart, productionPanelStart)

  assert.doesNotMatch(scriptPanel, /提取角色与场景/)
  assert.doesNotMatch(scriptPanel, /extract-compact-summary/)
  assert.doesNotMatch(scriptPanel, /data-extract-tab="characters"/)
  assert.doesNotMatch(scriptPanel, /data-extract-tab="scenes"/)
  assert.doesNotMatch(scriptPanel, /class="extract-card-grid"/)
  assert.doesNotMatch(page, /class="extract-table"/)
  assert.doesNotMatch(page, /<table class="extract-table"/)
  assert.doesNotMatch(page, /script:extract/)
  const productionBlockStart = page.indexOf('const productionBlockMessage')
  const productionBlockEnd = page.indexOf('const canExport', productionBlockStart)
  assert.ok(productionBlockStart > -1 && productionBlockEnd > productionBlockStart, 'production block helpers are present')
  const productionBlockHelpers = page.slice(productionBlockStart, productionBlockEnd)
  assert.doesNotMatch(productionBlockHelpers, /开始提取/)
  assert.doesNotMatch(productionBlockHelpers, /请先提取角色与场景/)
  assert.match(page, /goProductionBlockTarget[\s\S]*prodTab\.value = 'assets'/)
})

test('scene assets expose an update API for editable detail fields', () => {
  assert.match(apiSource, /update:\s*\(id:\s*number,\s*data:\s*any\)\s*=>\s*api\.put/)
  assert.match(apiSource, /`\/scenes\/\$\{id\}`/)
})

test('shot design and first-last frame generation are removed from the workbench', () => {
  assert.doesNotMatch(page, /生成首尾帧/)
  assert.doesNotMatch(page, /生成首帧/)
  assert.doesNotMatch(page, /生成尾帧/)
  assert.doesNotMatch(page, /frameMode/)
  assert.doesNotMatch(page, /frameModeOptions/)
  assert.doesNotMatch(page, /pendingShotFrame/)
  assert.doesNotMatch(page, /genShotFrame/)
  assert.doesNotMatch(page, /batchShotFrames/)
  assert.doesNotMatch(page, /getFirstFrame/)
  assert.doesNotMatch(page, /getLastFrame/)
  assert.doesNotMatch(page, /detail-preview-grid/)
  assert.doesNotMatch(page, /shotImgCount/)
  assert.doesNotMatch(page, /openGridTool/)
  assert.doesNotMatch(page, /宫格图/)
  assert.doesNotMatch(page, /prod:shots/)
  assert.doesNotMatch(page, /prodTab === 'shots'/)
})

test('studio theme exposes the redesigned professional palette hooks', () => {
  assert.match(studioCss, /--accent:\s*#4c8dff/)
  assert.match(studioCss, /--surface-base:\s*#15171a/)
  assert.match(studioCss, /--bg-base:\s*var\(--surface-base\)/)
  assert.match(studioCss, /--radius:\s*6px/)
})

test('episode workbench keeps the desktop rail at medium widths', () => {
  assert.doesNotMatch(
    page,
    /@media\s*\(max-width:\s*1240px\)\s*\{[\s\S]*?\.studio-body\s*\{[\s\S]*?grid-template-columns:\s*1fr/,
  )
  assert.match(
    page,
    /@media\s*\(max-width:\s*1080px\)\s*\{[\s\S]*?\.studio-body\s*\{[\s\S]*?grid-template-columns:\s*1fr/,
  )
})
